### ISSUE TITLE
US_#2_As a user, I want to be able to request for a quotation for a delivery

### ISSUE THREAD

**Issue by Julia-Trinh** [cristina-trofimov/WLW_soen343#3]
## Tasks:
- [x] Design UI for a quotation request
- [x] Implement quotation logic (same as in US_#1)

**Comment by YeeHawCordinator2** [comment]
mainly finished - i did not do much styling, will be done if we have extra time before the submission or maybe before presentation since for now it works fine

**Comment by YeeHawCordinator2** [comment]
done
